### ISSUE TITLE
length of 'dimnames' [2] not equal to array extent

### ISSUE THREAD

**Issue by batis2ta** [ccwang002/iGC#5]
Dear people, I am trying to sort out this problem.
at this step
 setattr(gene_exp_t, 'dimnames', list(NULL, shared_genes))
I get this error
Error in setattr(gene_exp_t, "dimnames", list(NULL, shared_genes)) : 
  length of 'dimnames' [2] not equal to array extent
I cant think of a reason why my expression data would not form a matrix and cant I setattr.
I will appreciate any help.
Best 
Mo

**Comment by batis2ta** [comment]
I dont get that with sample data

**Comment by ccwang002** [comment]
Hi I am no longer part of the lab, so I don't know how much time I have maintaining this project.

Could you explain what is the relationship of the command `setattr(gene_exp_t, 'dimnames', list(NULL, shared_genes))` and this package?

Because R has a quite complex data classes. A matrix may be a tibble, data.frame, data.table, and etc. It will be very helpful if you can provide a minimal working example so other people and reproduce your error easily.

Thanks.

**Comment by batis2ta** [comment]
No problem, a colleague rewrote the function, it uses simple data tables. You can close this.
